### ISSUE TITLE
Installation auf CCU (2.15.5) funktioniert nicht

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#14]
http://homematic-forum.de/forum/viewtopic.php?f=39&t=27751#p245717

CCU(2.15.5) 

Das Release 2.0 Lässt sich auf CCU2 leider nicht installieren.
Ich habe mal das CCU Log angehängt, vielleicht hilft das weiter ?

[homematic-ccu2-2015-11-16.txt](https://github.com/jens-maus/webmatic/files/35532/homematic-ccu2-2015-11-16.txt)

**Comment by jens-maus** [comment]
Tut mir leid, aber in dem logfile finden sich keine hilfreichen dinge. Was du aber machen kannst um das problem zu debuggen ist:
1. tar.gz via WebUI hochladen jedoch NICHT 'Installieren' drücken.
2. per SSH auf die ccu2 einloggen (während die CCU noch drauf wartet das du 'Installieren' drückst) und dort folgende Befehle eingeben und jeweils die Ausgaben/Fehlerangaben anschauen:
3. `/bin/update_firmware_pre`
4. `cd /`
5. `./update_script CCU2`

Es müsste dann hoffentlich der exakte Grund auftauchen warum er bei dir nicht in der Lage ist das tar.gz zu installieren. Wenn du dann die CCU2 neu booten willst (damit die wieder geht) am besten `/sbin/reboot` eingeben.

**Comment by homematic-wusel** [comment]
Hier das Ergebnis.... Habe darauf hin das Image nochmals heruntergeladen - Ergebnis identisch... 

/root$ /bin/update_firmware_pre
Entering firmware update mode
Extract firmware update file ...
Error unzipping firmware image archive. Rebooting

**Comment by jens-maus** [comment]
Bist du denn sicher das beim download das tar.gz (wie lädst du es denn runter) nicht irgendwie automatisch entpackt/verändert wird? die md5 summe sollte

`b9deaafc1229cbc1fb0648d520b035d7`

lauten. Ansonsten kann ich mir nur vorstellen das irgendwie dein tar.gz kaputt ist. du kannst ja mal statt dem /bin/update_firmware_pre einfach

`tar tvf /new_firmware.tar.gz`

aufrufen und schauen was er ausgibt ob das tar i.O. ist. Oder du schaust mal ob überhaupt durch den Upload alles i.O. auf der CCU2 angekommen ist:

`md5sum /new_firmware.tar.gz`

muss genau das oben liefern.

**Comment by jens-maus** [comment]
Ok, Fehler gefunden. Anscheinend verwendet Lissandro irgendeine andere Linux Umgebung zum generieren des Installationspaketes und das nimmt alles Dateien die executable rechte was wiederum dann dazu führt das die update_script datei nicht ausführbar ist -> Fehler wie oben gezeigt.

Bitte das 2.0 release Archiv wieder neu runterladen von hier:

https://github.com/jens-maus/webmatic/releases/download/v2.0/webmatic-2.0.tar.gz

sollte jetzt folgende MD5 Summe haben:

`6dc6bb2fe146f627a3accc5842f8658e`

**Comment by Apollon77** [comment]
Kannes bestätigen. Worx :-)
