### ISSUE TITLE
Systemvariablen nicht änderbar

### ISSUE THREAD

**Issue by homematic-wusel** [jens-maus/webmatic#15]
Im Version 1.x war es möglich auch Systemvariablen über Webmatic zu ändern. In Version 2.0 ist nur noch eine Anzeige möglich.

**Comment by ldittmar81** [comment]
Siehe: http://homematic-forum.de/forum/viewtopic.php?f=39&t=27552&start=20#p245442

Die Systemvariablen werden auch unter Sonstiges angezeigt, und da kannst es immer ändern. Du kannst auch in die Beschreibung der Variable ein (w) ... also ein w in Klammern... rein schreiben und dann kannst du diese auch oben bearbeiten. Option 3: wenn alle Systemvariablen bearbeitbar sein sollen, kannst du in der config.json, die sich im webmatic_user Ordner befinden sollte, den dazugehörigen Punkt auf false stellen.

Wird in der nächsten Version benutzerfreundlicher.
