### ISSUE TITLE
Unterstützung Funk-RGBW-LED-Controller

### ISSUE THREAD

**Issue by MrLee99** [jens-maus/webmatic#16]
Unterstützug von HM-LC-RGBW-WM
- Auswahl Helligkeit
- Auswahl Voreingestellte Programme
- Auswahl Farbe
- an/aus

**Comment by ldittmar81** [comment]
Hi Mr Lee,

ich brauche dafür 2 Sachen: Die Daten vom Gerät...

http://xxx.xxx.x.xx/addons/webmatic/cgi/list.cgi?list=xxxx

Wobei xxxx am Schluss durch die ID des Raumes/Gewerkes ersetzt wird. (Die ID findest du z.B. unter Sonstiges/Graphik IDs)

Und dann noch eine Zeichnung/Bild wie das auszusehen hat. Vielleicht ein Screenshot vom WebUI... oder irgendwie ein Beschreibung wie die einzelnen Attribute verändert werden sollen. (Knöpfe/Schieber/Eingabefeld oder irgendwas anderes)

Oder am Besten mir schenkt jemand so ein Funk-RGBW-LED-Controller, dann kann ich es live testen :sunglasses:

**Comment by MrLee99** [comment]
Schenken würde ich glatt machen..aber 20 Wochen Lieferzeit....
![unbenannt](https://cloud.githubusercontent.com/assets/15873710/11189129/b844466a-8c8e-11e5-872a-7c4695e91755.PNG)

**Comment by MrLee99** [comment]
![idee](https://cloud.githubusercontent.com/assets/15873710/11189326/cf2c1082-8c8f-11e5-9104-c84fe112483d.PNG)

**Comment by MrLee99** [comment]
```
{"name":"Wohnzimmer RGB Dimmer", "type":"CHANNEL", "id":"5696", "address":"[adress]:1", "hssType":"DIMMER", "visible":"true", "operate":"true", "channels": [
{"id":"5700", "type":"HSSDP", "hssType":"LEVEL", "value":"1.000000", "valueUnit":"100%", "date":"16.11.2015 17:37:54"},
{"id":"5701", "type":"HSSDP", "hssType":"OLD_LEVEL", "value":"", "valueUnit":"", "date":"01.01.1970 01:00:00"},
{"id":"5704", "type":"HSSDP", "hssType":"RAMP_TIME", "value":"", "valueUnit":"s", "date":"01.01.1970 01:00:00"},
{"id":"5702", "type":"HSSDP", "hssType":"ON_TIME", "value":"", "valueUnit":"s", "date":"01.01.1970 01:00:00"},
{"id":"5703", "type":"HSSDP", "hssType":"RAMP_STOP", "value":"", "valueUnit":"", "date":"01.01.1970 01:00:00"},
{"id":"5698", "type":"HSSDP", "hssType":"INHIBIT", "value":"false", "valueUnit":"", "date":"14.11.2015 13:38:22"}  ]
```

},
    {"name":"Wohnzimmer RGB Farbe", "type":"CHANNEL", "id":"5706", "address":"[adress]:2", "hssType":"RGBW_COLOR", "visible":"true", "operate":"true", "channels": [
    {"id":"5712", "type":"HSSDP", "hssType":"COLOR", "value":"200", "valueUnit":"", "date":"14.11.2015 13:41:13"},
    {"id":"5718", "type":"HSSDP", "hssType":"USER_COLOR", "value":"", "valueUnit":"", "date":"01.01.1970 01:00:00"},
    {"id":"5714", "type":"HSSDP", "hssType":"ON_TIME", "value":"", "valueUnit":"s", "date":"01.01.1970 01:00:00"},
    {"id":"5716", "type":"HSSDP", "hssType":"RAMP_TIME", "value":"", "valueUnit":"s", "date":"01.01.1970 01:00:00"},
    {"id":"5713", "type":"HSSDP", "hssType":"INHIBIT", "value":"false", "valueUnit":"", "date":"14.11.2015 13:38:22"}  ]
},
    {"name":"Wohnzimmer RGB Programm", "type":"CHANNEL", "id":"5719", "address":"[adress]:3", "hssType":"RGBW_AUTOMATIC", "visible":"true", "operate":"true", "channels": [
    {"id":"5730", "type":"HSSDP", "hssType":"PROGRAM", "value":"4", "valueUnit":"", "date":"16.11.2015 17:37:49"},
    {"id":"5733", "type":"HSSDP", "hssType":"USER_PROGRAM", "value":"", "valueUnit":"", "date":"01.01.1970 01:00:00"},
    {"id":"5728", "type":"HSSDP", "hssType":"ON_TIME", "value":"0.000000", "valueUnit":"s", "date":"14.11.2015 13:38:22"},
    {"id":"5731", "type":"HSSDP", "hssType":"RAMP_TIME", "value":"0.500000", "valueUnit":"s", "date":"14.11.2015 13:38:22"},
    {"id":"5727", "type":"HSSDP", "hssType":"INHIBIT", "value":"false", "valueUnit":"", "date":"14.11.2015 13:38:22"}  ]
},

**Comment by MrLee99** [comment]
Kanal1: einfach nen Dimmer
Kanal2: Schieberegler 0-200 (Farbe) 200= weiß; linear-gradient(to right, #ff0000 1%, #ffff00 18%, #00ff00 34%, #00ffff 50%, #0000ff 66%, #ff00ff 82%, #ff0000 97%, #ffffff 97.5%, #ffffff 100%)
Kanal3: Auswahlmenü für die Voreingestellten Programme 
Werte: 0;1;2;3;4;5;6
Beschriftung: OFF;Langsam; Normal;Schnell;Lagerfeuer;Wasserfall;Fernsehsimulation

**Comment by MrLee99** [comment]
Hab mal ne Spielversion zusammengetippt...nur mal zum spielen

Hab allerdings keinen Stich wie man jetzt den Slider in der LED-Farbe hinbekommt :-)
[webmatic.js.txt](https://github.com/jens-maus/webmatic/files/37902/webmatic.js.txt)
[wmmap.js.txt](https://github.com/jens-maus/webmatic/files/37903/wmmap.js.txt)

**Comment by ldittmar81** [comment]
Hi MrLee,

sehr gute Arbeit. Genau so wirds gemacht ;) ... ich bin aber schon an der Optimierung der Geräteliste dran, aber sobald das fertig ist, tue ich deine Änderungen hinzufügen.

Zu den Farben habe ich noch ein paar Fragen: Also... 200 = weiß... damit ich es besser verstehe: 1 sollte dann rot sein 100 sollte so ein hellblau sein, 36 = gelb, 68 = grün, 132 = dunkelblau, 164 = lila und 194 = rot (das gleiche wie 1) stimmt das? Was ist 199?

Das mit den Programmen: Stehen die Bezeichnung irgendwo? Die sollten doch irgendwo definiert sein... ich bekomme diese bestimmt vom Server, oder? Und was sind diese User-Programme? Kann man da eigene Programme hinzufügen?

Ohh... das wird schon ein komplexes Ding... besonders weil ich keins habe... hmm... ich sollte mir so ein Ding zulegen...

**Comment by MrLee99** [comment]
Programme: Werden so in der WebUI angezeigt, die Datenpunkte sind nur numerisch.

UserProgramme: Soweit bin ich ehrlich gesagt auch noch nicht...soweit habe ich mit dem Ding noch gar nicht gespielt...finde ich aber raus. Notfalls erstmal nen eingabefeld 1-99 zu auswahl?
Laut Anleitung kann man hier im expertenmodus eigene Programme hinterlegen..anscheinend von 1-99..

Farbe: Die anleitung hält hierfür einen schwarz/weiß gedruckten farbkreis bereit :-) Super...
Hier mal nen bischen info von fhem:
http://www.fhemwiki.de/w/index.php?title=HM-LC-RGBW-WM_Funk-RGBW-Controller&redirect=no

Da sind die schwellen für rgb drin. Weiß ist hardcoded 200 und und 0=199=rot

P.S.: aktuelle Lieferzeit 8 Wochen (!)....
P.P.s: so ganz ausgereift scheint die steuerung von dem Ding einfach nicht zu sein...erinnert an das Display...

**Comment by ldittmar81** [comment]
Danke für die Infos... genau das habe ich noch gebraucht. Wenn du das mit den User-Programme noch hin bekommst, kannst ja posten.
