### ISSUE TITLE
v2.0 hat als Titel immernoch 1.4

### ISSUE THREAD

**Issue by MrLee99** [jens-maus/webmatic#17]
Min!

Update manuell aus git. Nicht installer.

Seitentitel (links oben) immernoch 1.4?!? Oder mal wieder Cache?

bis denne
Mr.Lee

**Comment by MrLee99** [comment]
Leider immernoch.
Kommt ganz kurz 2.0 und wird dann überschrieben.

**Comment by ldittmar81** [comment]
Ich habe keine neue Installationsdatei gemacht... es ist im Code aber gefixt. Wollte eigentlich nicht eine Zwischenversion machen, nur um sowas kleines zu beheben. Wenn du aber die index.html durch die neue Datei ersetzt, dann sollte es gehen.

**Comment by jens-maus** [comment]
Ich würde auch nicht dafür plädieren dauern zwischenversionen zu machen. Wenn as problem eines Tickets als gefixt markiert ist sollte man natürlich auf die nächste version (das wäre dann 2.1) warten. Ich werde daher das ticket für milestone v2.1 markieren.

**Comment by MrLee99** [comment]
MoiN!

Neue Version nur nach erfolgreichem Test :-)

Teste allerdings aus dem Repo...
Ich check nochmal ob ich wirklich die richtige Version hab.

ggf. Könntet ihr "zwischen" 2 Versionen Buildcodes/revisionen vergeben dann kann ich meine Testinstallationen leichter unterscheiden..?

**Comment by jens-maus** [comment]
Das ist eher schwierig. sobald du die VERSION datei hier im hauptrepo änderst wird das installierte Haddon auf einer CCU immer denken es gibt eine neue version. Du musst halt einfach wissen was du tust. In den Fuß schießen kann man sich ja immer.... Und ehrlich gesagt ist dieser Thread hier wirklich schon viel zu lang für solch ein bedeutungsloses problem wie eine "falsche" Versionsnummer die irgendwo auftaucht :)

**Comment by MrLee99** [comment]
Dann will ich nur noch ein einziges mal den thread verlängern

a) ich weiß was ich tue (manchmal) und verwende die Daten direkt aus dem repo und eben nicht die installversion (s.o.)
b) zumindest bei meiner Inst ist das "Problem" noch da

Das Thema Testen und Versionierung /Revisionierung sheint tatsächlich diesen Rahmen zu sprengen.

Wenn Ihr  bedeutungslose Fehler nicht verfolgen wollt empfehle ich mit tags und prios zu arbeiten.

Ansonsten bin ich dann mal raus.

**Comment by ldittmar81** [comment]
Es gibt keine bedeutungslose Fehler. Nur Fehler und fatale Fehler. Ich habe mir ein paar Gedanken gemacht und ein paar Sachen angepasst. Einfach mal anschauen ob es passt.
