### ISSUE TITLE
Webmatic 2.0 kann auf CCU1 nicht installiert werden

### ISSUE THREAD

**Issue by hanoba** [jens-maus/webmatic#26]
Webmatic kann auf meiner CCU1 nicht installiert werden.
Nach dem Installationsvorgang ist Webmatic nicht als Zusatzsoftware aufgelistet. Ich habe sowohl webmatic-1.3beta.tar.gz als auch webmatic-2.0.tar.gz probiert.

Die Installation anderer Addons (HQ WebU, dropbear, XML-API) hat problemlos geklappt.

Ich habe versucht nach dem Firmware-Download von Hand (über ssh) zu installieren (laut Info in Issue#14):
 tar tvf /var/new_firmware.tar.gz

Hier kommt die Fehlermeldung: "tar: Invalid tar magic"

Gibt es einen Trick?

Danke und Gruß

Harald

**Comment by ldittmar81** [comment]
Leider bin ich kein Linux experte... eigentlich kenne ich mich null mit Linux aus. Vielleicht hat der jens eine Idee...

**Comment by hanoba** [comment]
Als workaround kann die  Installation wie von ldittmar81 beschrieben (http://homematic-forum.de/forum/viewtopic.php?f=39&t=27751&start=30#p247246) manuell durchgeführt werden. Das hat bei mir geklappt.
Ich kann Webmatic über .../addons/webmatic/ aufrufen. Allerdings gibt es noch zwei Schönheitsfehler: Webmatic wird nicht vom WebUi als installiert aufgelistet und als Webmatic Versionsnummer wird noch 1.4 angezeigt.
