### ISSUE TITLE
Endlosschleife im Menupunkt Systemvariablen

### ISSUE THREAD

**Issue by GerdS1960** [jens-maus/webmatic#27]
Hallo.

Habe gestern erstmalig die 2.0 auf meiner CCU2 installiert. Die Oberfläche sieht schonmal toll aus.
Nur beim Aufruf der Systemvariablen läuft die Sanduhr endlos ohne dass sich der Bildschirm füllt.

Bin ich der erste, bei dem das auftritt und was kann ich tun, um die Fehlerursache einzugrenzen?

Grüße

Gerd

**Comment by ldittmar81** [comment]
Hi Gerd,

ein Grund dafür könnte vielleicht sein, wenn du Variablen mit einem " im Wert hast... zum Beispiel HTML Text... eine Lösung dafür habe ich auch schon und das wird in Version 2.1 integriert sein.

Grüße,
ldittmar

**Comment by GerdS1960** [comment]
Hallo.

Auch schon in der alpha? Dann würde ich es mal testen.

Grüße - Best Regards

Gerd Schelbert

**Comment by ldittmar81** [comment]
Hi Gerd,

so schnell bin ich nicht :stuck_out_tongue_winking_eye: ... es wird in Alpha2 drin sein.

Grüße,
ldittmar
