### ISSUE TITLE
Diagramme werden nicht dargestellt

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#28]
von schneider.obw

Ich verwende die Graphen/Tachoanzeige (oder wie die Dinger auch
immer heißen) für Anzeige von Einzelwerten von Sysvars - ebenfalls gemäß
Konfiguration aus der V1.x. (Start, Endwert, Farbe, ...). Hier zeigt sich
der Effekt, dass die Tachos erst nach dem zweiten Laden des Untermenüs im
Browser erscheinen. Sprich: Submenü aufrufen, Tacho nicht da - anderes
Submenü wählen - zurück zum ersten Submenü: Tacho erscheint. Ich verwende
Feuerfuchs in aktuellster Version.

Für die beiden oben beschriebenen Funktionen habe ich dabei die jeweiligen
SysVars bzw. Diagramme (als SysVars) in einem Favoriten definiert.

**Comment by schneiderobw** [comment]
Hallo.
Zu diesem Issue habe ich ein aktuelles Update:
Nachdem ich die Alpha1 und jetzt auch die Alpha2 runtergeladen habe, musste ich feststellen, dass (spätestens) mit der Alpha2 jetzt auch die Hauptseite/Startseite von Webmatic bei einem jungfräulichen Browser beim ersten Aufruf nicht angezeigt wird (Cache geleert). Erst beim nächsten Reload (F5) funktioniert alles ordentlich.
Das Problem mit den Tachoanzeigen und Diagrammen (Anzeige ebenfalls erst beim erneuten Reload) besteht weiterhin.
Das Problem ist bei all meinen Browsern unter Win7 gleich (Firefox 42, IE 9.x, Safari), und auch jeweils getrennt innerhalb der Browser.
Temporäre Dateien im Java-Cache habe ich ebenfalls mal geleert, Verhalten unverändert.

Ich habe leider keine Erklärung für diese Effekt.
Und es ist auch möglich, dass beide Phänomene noch getrennte Gründe bzw. Ursachen haben.
Ich helfe bei Bedarf gerne mit Debugging.
![unbenannt](https://cloud.githubusercontent.com/assets/16177943/11791664/5ddb8b3c-a2a2-11e5-92b0-65f180fab842.JPG)

**Comment by ldittmar81** [comment]
Da bin ich noch dran.... Ist echt komisch.

**Comment by schneiderobw** [comment]
Kannst du es denn nachvollziehen?
Vielleicht hat es was mit dem Laden der Bibliotheken von/für Java zu tun…
Mittlerweile braucht es diesen doppelten Reload ja auch beim ersten Aufruf der Startseite.
Ich teste gleich mal die Alpha3.

Update - Alpha3: Problem des ersten Doppel-Laden der Startseite schien zunächst beim ersten Aufruf gelöst. Ich hatte dazu die Webmatic inkl. aller Settings (webmatic_user) auf der HM komplett deinstalliert und gelöscht. Und die Seite lud nach Neuinstallation (und frischem Browser) dann auch gleich beim ersten Mal durch (hat zwar bissl länger gedauert - vermutlich wegen der Init der config-Dateien). Leider dann aber beim nächsten Versuch der gleiche Effekt (wieder mit frischem = leerem Browsercache, aber HM im letzten Zustand).
Problem existiert also noch für beide bzw. alle drei Fälle: 
Doppeltes Laden für Grafiken und Tachoanzeigen
Doppeltes Laden beim ersten Start 
Vielleicht hat es ja was mit Caching oder Buffer in der HM zu tun?
(Oder evtl. mit dem Laden der config-Daten aus WM heraus.)

Meine Umgebung ist Win7 64 Bit und aktuelle Java – 32 uns 64 Bit installiert. Je nach Browser.
Und es ist auf allen Browsern gleich….
Update: Übrigens auch auf allen i-Apple-Geräten exakt gleiches Verhalten wie in der Windows-Umgebung. Problem ist also wohl im Code bzw. auf der Serverseite liegend.

**Comment by ldittmar81** [comment]
Es ist bestimmt ein Timing-Fehler. Ich werde mich die nächsten paar Tage
auf Timing, Optimierung und Bugfixing konzentrieren. Ich finde da bestimmt
was :)

Am 17. Dezember 2015 um 07:56 schrieb schneiderobw <notifications@github.com

**Comment by ldittmar81** [comment]
Ich schiebe mal auf 2.2, denn da werde ich mich ganz auf die Variablen konzentrieren und prinzipiell gehts ja...

**Comment by schneiderobw** [comment]
Hallo.
Das scheint jetzt mit der Alpha 2.2. zu funktionieren.
Zumindest bekomme ich alle Graphen und Tachos beim ersten Laden angezeigt.
War bestimmt ein Timing-Problem, und du hast es entdeckt/gefixt... oder hat sich evtl. auch von alleine korrigiert durch Zusammenspiel mit anderen (geänderten) Ladezeiten.
Auf jeden Fall kannst Du den Issue hier zu machen. Lädt jetzt alles korrekt.

Grüße
schneider.obw

**Comment by ldittmar81** [comment]
Cool... das sind mir die liebsten Fehlern :stuck_out_tongue_winking_eye:
