### ISSUE TITLE
Icons für Programme

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#3]
Die Möglichkeit Bilder zu den einzelnen Geräte, Programme oder Variablen hochzuladen.

**Comment by schneiderobw** [comment]
Hallo.
Könntest Du evtl. die Anzeige von hinterlegten Icons für Programme auch unter den Favoriten anzeigen lassen?
Unter dem Menüpunkt Programme funktioniert es:
![unbenannt](https://cloud.githubusercontent.com/assets/16177943/13197396/17a93f3a-d7ed-11e5-806e-20946b893223.JPG)

Bei einem Programm unter Favoriten aber leider nicht:
![unbenannt2](https://cloud.githubusercontent.com/assets/16177943/13197398/37eb9144-d7ed-11e5-9936-e58b8b3ce34d.JPG)

Entweder wurde es noch nicht bedacht - oder es ist ein Bug (oder beides ;-).
Nur als Anregung/Hinweis.

**Comment by schneiderobw** [comment]
Hallo ldittmar,
bist Du sicher, dass dieses Issue mit der V2.2 closed ist?
(Changelog V2.2: Bugfix: Programmbilder werden auch unter Favoriten angezeigt)

Ich arbeite mich gerade durch die 2.2 durch, um meine GUI mit den neuen Funktionen aufzupeppen, konfiguriere dabei ein Programm mit "nur Grafik". Dieses wird im Menüpunkt Programme dann auch ordentlich mit Grafik angezeigt; das gleiche Programm als Objekt unter meinen Favoriten jedoch nicht.

Evtl. hast Du ja nur vergessen, den Code auf Github zu schieben.

Und vielleicht noch ein Enhancement (wenn Du schon grad an diesem Codesegment bist ;-):
Könntest Du ermöglchen, auch Icons kleiner 160x160 größengerecht einzublenden; sonst tragen die Teile in den Programmen zu dick auf. Anbei mal ein Beispiel für ein Icon 80x80. Die kleineren Icons braucht es meiner Meinung nach im Datenfeld rechts durchaus. Kannst ja mal schauen, was geht.

![unbenannt](https://cloud.githubusercontent.com/assets/16177943/13775189/78d4bf28-eaa3-11e5-9e3a-32de6ba03fbb.JPG)

Danke und Grüße
schneider.obw

**Comment by schneiderobw** [comment]
Nachtrag zum Thema Iconsgröße:
Wenn in den Einstellungen Bearbeiten-Programme die Funktion "nur Grafik" auf Nein steht, dann wird die Größenskalierung von kleineren Icons berücksichtigt (ändert aber nichts am o.a. grundsätzlichen Problem  keine Icons für Programme in Favoriten).

![unbenannt](https://cloud.githubusercontent.com/assets/16177943/13775555/7d4cf24e-eaa5-11e5-8a4d-ef3aa1799a52.JPG)

**Comment by ldittmar81** [comment]
Hi schneider.obw,

diese neue Anzeigeart "nur Grafik" ist eher für die Darstellung ohne feste Spalten gedacht. Wenn die anzahl der Spalten auf "auto" gestellt wird, dann erscheinen alle Programme oder auch Variablen die auf "nur Grafik" stehen in gleich große Vierecke. Die Größe wurde auch so gewählt, dass man z.B. bei den Variablen noch ein paar Informationen drunter schreiben kann. Ich wollte damit erreichen, dass man eine Seite bekommt, die gleich große Objekten enthält. Außer man möchte ein Objekt in groß darstellen (dieser dann nicht als "nur Grafik").

Für die nächste Version ist aber auch schon in Planung einzelnen sichten, mit verschiedene Anzahl von Spalten zu erstellen.

Grüße,
ldittmar

**Comment by ldittmar81** [comment]
Ich persönlich würde grundsätzlich große Icons hochladen... Man kann auch riesen Fotos hochladen. Ich tue eh alle Bilder in 160x160 speichern... und in der kleine Version wird es nur 80x80 dargestellt.

Hier noch ein Beispiel für die Umsetzung: http://homematic-forum.de/forum/viewtopic.php?f=39&t=27751&start=170#p268264

**Comment by ldittmar81** [comment]
Ohh... werden keine Icons in Favoriten angezeigt? Hmm... ich schaue später nochmal mach, aber ich bin mir sicher, dass es mal eine Zeit lang ging. :thought_balloon:

**Comment by schneiderobw** [comment]
Na ja. Ich bin halt mit meiner GUI eher zeilenorientiert, und habe jede neue Funktion lieber in einer eigenen Zeile. Und dann schauts mit den kleinen Icons eben richtig gut aus. Und bei den Programmen selbst geht es ja auch schon wunderbar.

![unbenannt2](https://cloud.githubusercontent.com/assets/16177943/13776939/335e193a-eaad-11e5-8988-05c67733246d.JPG)

Zum Thema Icons in Favoriten:
Ich hatte gesehen, dass Du diesen Bug plötzlich als closed getagged hast, ich habe die Funktionalität aber noch nie in einer Alpha oder auch anderer Zwischenversion gesehen.

**Comment by ldittmar81** [comment]
Jepp... jeder hat seine Vorlieben.. was das Programmieren extrem kompliziert macht, aber wenn die Komplexität steigt, steigt auch der Programmier-Fun-Faktor :laughing: 

Wie dem auch sei. Ich schließe nur Sachen, die auch wirklich fertig sind... hmm... also: Wir reden von Programme, die in den Favoriten aufgenommen wurden oder? Ohh... ich war mir sicher, dass ich es gefixt hatte... ohh... ich werde alt. :older_man: Ich schaue mir das ganze später nochmal an und fixe es noch für Version 2.2.1... und wenn du noch was finden solltest, dann her damit. ... und sorry... war mir echt sicher es gefixt zu haben. Hab vielleicht nur geträumt :sleeping: :zzz:
