### ISSUE TITLE
kleine kosmetische Korrektur an Textformat der Zeitanzeigen

### ISSUE THREAD

**Issue by schneiderobw** [jens-maus/webmatic#32]
1. Zeitanzeige hinter Objektdaten zeigt "vor 99 Tage" (fehlt das "n").
2. Und es wäre schön, wenn die Textgröße für die Zeitanzeige bei Sysvars auch im gleichen Format erscheint wie bei anderen Datenobjekten.

Beiliegende Snapshot zeigt ein Beispiel:
Rolladenstatus ist eine SysVar vom Typ Text, die Zeitanzeige ist anders, als bei den beiden Objekten darunter. Licht_Küch..... sind beides Progammaufrufe (in einem Favoriten) - bei Licht_Küche_Wechseln fehlt das "n" (bei mehreren Tagen).
Der Snapshot stammt aus einem Favoriten aus der Favoritengruppe.
1. Wennz gleich in den Code von den Zeitanzeigen geht, wäre es evtl. noch eine Idee, diese über eine globle Einstellung in einer .json für alle Objekte global aus- bzw. einzublenden. Es mag User geben, die wollen die Info nicht sehen (auch wenn dann auf die Datenintegrität kein Verlass ist).

Pkt. 1+2 sind rein kosmetischer Art.
Pkr. 3 wäre eine function nice to have.
![zeitanzeigen_snap](https://cloud.githubusercontent.com/assets/16177943/11656047/da445432-9db2-11e5-8fec-b532a3e39eba.JPG)

**Comment by ldittmar81** [comment]
Das mit Tagen ist gefixt, das andere schiebe ich auf 2.2, weil ich mich dann ganz um die Variablen widmen werde... WebMatic wird noch der Hammer werden :laughing:

**Comment by schneiderobw** [comment]
Jetzt wäre es cool, evtl. die Schriftgrößenanpassung bei der Darstellung der Sysvars vorzunehmen.
Erstes Bild zeigt ein Objekte (in Favoriten) mit Programmen und Sysvar nebeneinander. Die Zeitanzeige bei Sysvar ist unter dem Text, und beinhaltet noch eine zusätzliche Zeile mit der Beschreibung.
![unbenannty](https://cloud.githubusercontent.com/assets/16177943/13062961/66ace684-d443-11e5-9d9b-f22f76701484.JPG)

Meine Wunschvorstellung - auch, um bei den Objekten in 2-spaltig etwas mehr Ruhe reinzubringen - passe die Darstellung für Sysvars an:
a) streiche Beschreibung komplett (da stehen eh oft noch Konfig-Daten drin
b) bringe die Zeitanzeige hinter den SysVar-Wert und im gleichen Format wie Zeitanzeige bei allen Objekten. Das Textformat für die Sysvar kann gerne so bleiben - zur Unterscheidung.
![unbenanntz](https://cloud.githubusercontent.com/assets/16177943/13062962/6b249c52-d443-11e5-9026-979778e540a9.JPG)

Und ganz genial wäre noch, wenn Du die Zeitanzeigen wählbar ausblenden könntest - konfigurierbar in den globalen Einstellungen, oder auch zusätzlich noch gerätebezogen.

**Comment by ldittmar81** [comment]
zu a) - Unter Einstellungen > Optionen > Systemvariablen optional auschaltbar
zu b) - Ist ja der ursprüngliche Wunsch... geht klar
zu genial wäre - Klar doch: Unter Einstellungen > Optionen > Systemvariablen wird es zu finden sein

**Comment by schneiderobw** [comment]
wie ich sehe, hast Du es schon aufgenommen.
dennoch schieb ich als Argumentationshilfe noch ein Bildchen hinterher.
schau mal, wieviel Platz durch die 3-zeilige Darstellung hier insgesamt verloren geht
(bzw. dann bald gegangen ist ... ;-):

![unbenanntzz](https://cloud.githubusercontent.com/assets/16177943/13063305/fd76389c-d446-11e5-849c-48fa93886a3c.JPG)

**Comment by schneiderobw** [comment]
hmmmm. Man sollte auch immer mal über den Tellerrand schauen (bzw. alle möglichen Varianten berücksichtigen). Wenn Du die Darstellung/Position der Zeitanzeige für SysVars moddest, beachte bitte, dass es bei Wertefelder etwas knapp werden könnte:
![unbenannt](https://cloud.githubusercontent.com/assets/16177943/13063836/9b3f3d9e-d44c-11e5-9526-d9c48de9e471.JPG)

Das hier nur noch als Input - einen guten Lösungsvorschlag hab ich leider nicht zur Hand (außer: Zeitanzeigen ausblenden, was bei mir dann sowieso passieren wird ;-)

**Comment by ldittmar81** [comment]
Sowas ist schon seit Version 2.1 teilweise schon eingebaut und zwar wenn man mehr als 6 (oder 7) Elementen hat, dann wechselt es automatisch in eine andere Darstellung. Ist auch schon zum Glück in weiser Voraussichtlich so gebaut worden, dass man es auch auswählbar machen kann. Wird also auch in 2.2 kommen... ich hätte auch eine dritte und vierte Darstellungsweise, die kommen aber erst in 2.3 und 2.4 😉

**Comment by ldittmar81** [comment]
Fixed with commit 30aebf119222f275c93d10e2624f793f045cc55e

Ich denke es wurde alles umgesetzt. Wenn nicht dann bitte ein neuen Issue mit genaue Beschreibung öffnen.

**Comment by schneiderobw** [comment]
Hallo ldittmar.

In der Alpha 2.2-1 hab ich in den Einstellungen für SysVars bei größeren Textfeldern deine unten erwähnten Optionen gefunden.

Nur scheints leider noch nicht richtig zu funktionieren (oder ist noch nicht zu Ende programmiert).

Effekt:

Beim Ändern von auto auf button oder select und dann auschecken mit dem Häkchen ändert sich nichts an der GUI (auch nicht nach Reload und/oder Ctrl F5).

Geht man dann wieder in die Einstellungen, ist das Teil wieder auf auto zurück gesprungen.

Die zugehörige Definitionszeile in der Variables.json hat dabei unter listType dauerhaft den Wert „auto“:

"40483":{"name":"Rolladenastroautomatik","oldname":"Rolladenastroautomatik","visible":true,"oldvisible":true,"position":62,"value":"0","operate":"none","oldoperate":"none","date":"20.02.2016 15:46:47","info":"Rolladensteuerung%20Astroautomatik","valueType":"16","valueUnit":"","valueList":"Astroautomatik aus; Astro morgens; Astro abends; Astro morgens/abends","listType":"auto"},

Wennz noch nicht fertig codiert ist, dann iss gut.

Ansonsten schau mal, ob nicht doch noch ein Bug.

Von: ldittmar [mailto:notifications@github.com] 
Gesendet: Dienstag, 16. Februar 2016 06:58
An: jens-maus/webmatic
Cc: schneiderobw
Betreff: Re: [webmatic] kleine kosmetische Korrektur an Textformat der Zeitanzeigen (#32)

Sowas ist schon seit Version 2.1 teilweise schon eingebaut und zwar wenn man mehr als 6 (oder 7) Elementen hat, dann wechselt es automatisch in eine andere Darstellung. Ist auch schon zum Glück in weiser Voraussichtlich so gebaut worden, dass man es auch auswählbar machen kann. Wird also auch in 2.2 kommen... ich hätte auch eine dritte und vierte Darstellungsweise, die kommen aber erst in 2.3 und 2.4 😉

**Comment by ldittmar81** [comment]
Ohh... da habe ich ja was vergessen. :scream: Wird bei der nächste Version gehen
