### ISSUE TITLE
Fehler bei Anzeige Rolladenaktoren - Slider und Wertefeld 0...100%

### ISSUE THREAD

**Issue by schneiderobw** [jens-maus/webmatic#43]
Hallo ldittmar.

Ich möchte Dir über einen kleinen Bug mit den Objekten der Rolladenaktoren berichten, der einfach nachvollziehbar und sicher auch einfach zu lösen ist:

Der Wert bei den Rolladenslidern für die Rollladenposition im Feld links neben dem Slider wird von 0 bis 1 dargestellt, repräsentiert dabei aber die Stellung von 0 bis 100%.
Setzt man nun mit den Buttons für den Festwert eine Prozentzahl  (20/40/60…%), geht der Rolladen in die richtige Position - das Feld aber zeigt 0.6, und der Slider steht auch auf 0.6 (bei einer Skalierung bis 100(%). Schiebt man den Slider über die 1 hinaus (also alles von 1,01 bis 100), dann geht der Rolladen voll auf.
Du müsstest also die Umrechnung von 0…1 = 0…100% im Wertefeld beim Slider und für den Slider selbst noch anpassen.

Das Bild anbei noch zur Veranschaulichung.
![2015-12-12 18 57 27](https://cloud.githubusercontent.com/assets/16177943/11783630/8aab3f9c-a278-11e5-88e8-31381dd3acb9.png)

Ich teste übrigens auf meiner CCU2 immer mit dem aktuellsten Code hier aus dem GitHub,
also derzeit die Alpha2, aber noch upgedatet mit allen neuen Dateien aus dem CCU2-Verzeichnis hier (= letztes Änderungsdatum gestern).

**Comment by ldittmar81** [comment]
Hi... der Fehler ist schon "ewig" (Alpha1) drin und erst jetzt wurde es bemerkt? :-O ... Hmm... ok... ich habe es auch erst gestern abend durch Zufall gesehen :-P Danke für die Meldung. Beim nächsten Upload ist es gefixt ;-)

**Comment by akwak2015** [comment]
;-) Das gleiche Verhalten zeigt auch der LED RGBW-Dimmer. Hab ich bewust aber noch gar nicht wahrgenommen, da ich 0,2 automatisch mit 20% assoziiere und den Slider selten nutze da ich den mit meinen Griffeln sowieso nie auf den gewünschten Wert bewegt bekomme.
Gruß,
Alfred

**Comment by schneiderobw** [comment]
Na ja: der Slider für die Rolläden ist schon eine gute Methode zur Einstellung (egal, ob man den nun beim Loslassen oder erst mit Bestätigung haben will - siehe Issue #18).
Und in das Wertefeld trag ich auch lieber eine Zahl zwichen 0 und 100 ein, statt auch noch mit einem Komma rumzufummeln. (Und wie soll ich das mit dem Null-Komma-x denn meiner Frau noch erklären ;-).
Aber zum Glück hat Idittmar ja easy-going den Fix schon im Vorlauf. Danke auch dafür!!

**Comment by ldittmar81** [comment]
Tja... ich tue mein Bestes 😉. Aber mal was anderes: hat jemand das neue Feature gesehen und verstanden? Naja... noch funktioniert es nicht, aber wenn es fertig ist wirds richtig cool. (Hoffe ich) Aber es ist ja eine Überraschung und deswegen existiert kein Issue dafür 😊

**Comment by schneiderobw** [comment]
Na dann spann mich mal nicht so auf die Folter ….
Ich arbeite viel mit der Alpha2 und den neueren Weiterentwicklungen im aktuellen Code.
Die neuen Settings für sämtliche Objekte und deren Positionen im Einstellungsmenü habe gesehen, und auch schon alle durchgespielt: funktioniert alles gut.
Ein (weiteres) neues (verstecktes) Feature ist mir noch nicht unter die Maus gekommen.

**Comment by ldittmar81** [comment]
Naja... dann bist du bestimmt drüber gestolpert. Wie gesagt: es funktioniert noch nicht, aber beim nächsten Upload wird es drin sein. 😉 Ist ja auch nicht für jedem... man muss noch was haben damit es geht. Aber wie gesagt: Surprise 😈

**Comment by ldittmar81** [comment]
Jetzt gehts wieder :)
