### ISSUE TITLE
Optionen für dieses Gerät - Fehlfunktion

### ISSUE THREAD

**Issue by schneiderobw** [jens-maus/webmatic#44]
Beim Test im Bereich "Optionen für dieses Gerät" eine Fehlfunktion in der Alpha2 (mit Update der letzten Codeaktualisierungen vom So 13.12.) festgestellt.
Das Programm schreibt die gewählten Einstellungen für SysVars nicht in die config_IP.json und bleibt damit immer stehen auf "nicht ausgewählt".
Snapshot anbei sowie die erzeutgen .jsons (diese umbenannt in .txt zum Uploaden hier auf Github).

![unbenannt](https://cloud.githubusercontent.com/assets/16177943/11820543/711d546e-a365-11e5-8a37-23e503559c7d.JPG)

[config192.168.178.31.json.txt](https://github.com/jens-maus/webmatic/files/63067/config192.168.178.31.json.txt)
[config.json.txt](https://github.com/jens-maus/webmatic/files/63068/config.json.txt)

**Comment by ldittmar81** [comment]
Danke :+1: Ich kümmere mich drum.
