### ISSUE TITLE
Buttons werden falsch umgebrochen

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#46]
QLink schreibt:

Darstellungsproblem bei dem "Optionen für dieses Gerät" Menü. (siehe Screenshot)

![webmatic](https://cloud.githubusercontent.com/assets/9552828/11919789/289e4d7e-a75c-11e5-8bb9-6ddff3ee2184.PNG)

**Comment by schneiderobw** [comment]
Hallo.
Wenn ich das richtig sehe, dann liegt das einfach daran, dass die Buttons quasi einen Zeilenumbruch machen (hinter "globale Einstellungen") weil der Rest nicht mehr in eine Zeile geht.
Da aber offensichtlich noch ausreichend Platz, ist evtl. einfach die Abfrage auf die Fenstergröße irgendwie noch zu berücksichtigen.
Nur als Hinweis.

**Comment by ldittmar81** [comment]
Hi,
das Problem ist dass WebMatic auf das nicht so optimale jQuery Mobile aufbaut... das gibt es nur div mit gleicher Aufteilung... also 50%/50% oder wie hier 33%/33%/33% ... naja... deswegen ist irgendwann kein Platz mehr, auch wenn eigentlich noch 33% der Zeile ungenutzt ist... ich habe jetzt eine neue Variante programmiert 33%/66% ... Ich muss jetzt nur schauen dass es überall gut aussieht... und vielleicht brauche ich noch eine 33%/50%/16% ... aber das muss ich noch sehen. Wenn das Ganze auf Bootstrap bauen würde, dann wäre es schöner, aber man kann ja nich ales haben :laughing:
