### ISSUE TITLE
Zusatztext bei Homematic Internen Geräten

### ISSUE THREAD

**Issue by schneiderobw** [jens-maus/webmatic#48]
Hallo.
Kleine Korrektur für die Anzeige der Internen Geräte (virtuelle Fernbedieung - HM-RCV-50 BidCos:xx).
Diese internen Geräte verwende ich als Schalter, um über direkte Verknüpfungen mehrere verknüpfte Geräte zu steuern.
In der Anzeige für diese Geräte wird unter den Bedienknöpfen ein unklarer Zusatztext eingeblendet (NaN % - Virtual Key Level ...).
Siehe Foto anbei: Alle_Rolladen_Sonne und Alle_Rolladen_Zu sind virtuelle Fernbedienungen HM-intern, Rolladen_Gruppe_KU_Auf ist ein externer Taster - hier ist die Anzeige ok.

![unbenannt](https://cloud.githubusercontent.com/assets/16177943/11973344/1ffb27ec-a959-11e5-8fb0-d568e6e99dbc.JPG)

Die Geräte in der Homematic sind die folgenden:

![unbenannt2](https://cloud.githubusercontent.com/assets/16177943/11973325/e8e29bb4-a958-11e5-87fc-9d03685b1e08.JPG)

Der Datenstrom meines Gewerkes Rolladen (mit div. echten und virtuellen Geräten) anbei:
[Virtuelle_Taster.txt](https://github.com/jens-maus/webmatic/files/70555/Virtuelle_Taster.txt)

**Comment by schneiderobw** [comment]
BTW - Nachtrag:
Diese virtuellen Geräte können auch Zwischenwerte annehmen. Bei mir ist z.B. Rolladen_Sonne mit mehreren Rolladenaktoren in einer direkten Verknüpfung. Das virtuelle Geräte verhält sich in dem Fall wie ein Rolladenaktor und nimmt kurze/lange Tastendrücke, aber auch %-Werte (z.B. in einem Script) für die Rolladenposition an.
Vielleicht ist das noch ein Hinweis, warum diese Anzeige hier zusätzlich auftaucht.

**Comment by ldittmar81** [comment]
Ich habe es mal vorerst ausgeblendet und wenn ich dann in Version 2.3 mich mit den Geräte beschäftige, dann schaue ich es mir genauer an ;-)
