### ISSUE TITLE
Installation von WB 2.1.2 auf CCU2 nicht möglich

### ISSUE THREAD

**Issue by ghost** [jens-maus/webmatic#53]
CCU2 mit FW 2.15.5

Installation von WB 2.1.2 -> Neustart der CCU2

IST:
- das Interface ist unter der URL <ip>/addons/webmatic nicht zu erreichen (404)
- das Addon taucht nicht unter Zusatzsoftware auf

**Comment by ldittmar81** [comment]
Hi holwes,

ich habe auch eine CCU2 und da habe ich es mehrmals problemlos installiert. Bis jetzt habe ich auch nicht gehört dass es irgendwo anders nicht funktioniert. Wie hast du es installiert? War das eine Neuinstallation oder hast du schon vorher eine andere Version installiert?

**Comment by ghost** [comment]
Sorry, das war mein Fehler. Ich habe das tar.gz per Safari heruntergeladen, welcher das File sofort dekomprimierte und lediglich das tar-Archiv hinterließ. Das schluckte zwar die CCU2, jedoch installierte es nicht. Mit FF funktioniert alles wunderbar :-)
