### ISSUE TITLE
Mehrere Spalten in allen Anzeigen nebeneinander

### ISSUE THREAD

**Issue by taylortom96** [jens-maus/webmatic#57]
Toll wäre eine Anzeige mehrerer Elemente nebeneinander, besonders wenn das Display entsprechend breit ist. Eine Festlegung der Spaltenanzahl in den Einstellungen oder eine automatische Anpassung an die Breite und Ausrichtung des Displays wäre großartig. Damit wäre nämlich auch ein Statusdisplay möglich.

**Comment by ldittmar81** [comment]
Sowas in der Art habe ich schon im Hinterkopf. Es wird aber erst mit Version 2.4 kommen, denn vorher müssen noch die Variablen und Geräte schöner werden :smile:

**Comment by schneiderobw** [comment]
Grad eben wollte ich ein Issue hier im Github  von mir aktualisieren, da sehe ich, dass Du nochmal ein Update des Codes mit dem Stichwort hier "Kampf mit den Spalten" hochgeladen hast. Das spiel ich grad noch ein und probiers mal aus - aber was genau ist/war das Problem mit den Spalten??

**Comment by ldittmar81** [comment]
Das größte Problem war, dass die einzelnen Objekten verschiedene Höhen hatten. Das hat dazu geführt, dass das ganze Bild total unruhig wurde, wenn viele Elementen vorhanden waren.
Ich wollte dass die Einstellungen 1-Spaltig bleiben. Die Einstellungen sind ja schließlich nur zum Einstellen da und da braucht man schon viel Platz.
Und letzter Punkt: ich wollte alles noch ein bisschen flexibler machen... ich habe gemerkt, dass man z.B. im Büro gerne 4 Spalten hätte, aber ein Raum mit viele Diagrammen sollte 1-Spaltig bleiben (das geht noch nicht, kommt aber früher oder später...)
Soviel dazu... Kommentar zur andere Sache kommt per Mail... :smile:

**Comment by schneiderobw** [comment]
ok. hab mal die neue Version getestet, und ich denke, ich habe den Unterschied gefunden.
vorher hattest Du keinen Ausgleich bei unterschiedlichen Blockgrößen - siehe Bild 1 erstellt mit der Vorversion.
![unbenanntx](https://cloud.githubusercontent.com/assets/16177943/13062763/14a255f6-d441-11e5-9a41-1fff5ef60ec7.JPG)
Und in der aktuellen Version von heute (gestern vor 6 Minuten) schaffst Du den Ausgleich abhängig von der Höhe der Objekte gegeneinander - siehe Bild 2.
![unbenannty](https://cloud.githubusercontent.com/assets/16177943/13062818/a77d62da-d441-11e5-9af7-2a33174532f1.JPG)
Das ganze wird sicherlich bei Objektenblöcken mit sehr unterschiedlichen Höhen sehr wirksam sein. Aber es erinnert mich speziell für meinen Fall noch an ein Issue, das ich hier bereits aufgemacht habe. Ich stelle auch dort mal eine Aktualisierung ein, weil ich denke, es wäre eine gute Gelegenheit, das in die aktuelle Entwicklung mit einfließen zu lassen.
Die Grafiken und Erläuterung hier primär für alle User, die sich das mal anschauen wollen.
