### ISSUE TITLE
Ansichten selbst festlegen 

### ISSUE THREAD

**Issue by taylortom96** [jens-maus/webmatic#58]
Zusätzlich zu den vorhandenen Möglichkeiten wäre es toll, wenn man eigene Ansichten  definieren könnte, in denen verschiedene Geräte, Kanäle, Systemvariablen gemischt werden könnten.

**Comment by ldittmar81** [comment]
Das geht doch schon... einfach Favoriten in der CCU anlegen. Was noch dazu kommen wird, ist das "einfache" Anbinden von Programme und Variablen an Räume und Gewerke.
