### ISSUE TITLE
Radio Einbindung

### ISSUE THREAD

**Issue by zahnheinrich** [jens-maus/webmatic#59]
Schön wäre es, wenn bei vorhandener URL nicht diese, sondern direkt die Station angezeigt würde.
![radio](https://cloud.githubusercontent.com/assets/16634531/12222006/c527e7ec-b7ae-11e5-8f8c-688fb928a679.png)
So wie die erste Station.
Nach Verlassen des Menues erscheint beim nächsen Zugang wieder die URL

**Comment by ldittmar81** [comment]
Wenn du die Variable auf (readonly) stellst, dann ist es so... dann erscheint direkt der Sender. Bei Version 2.2 werde ich mich auf die Variablen konzentrieren. Ich wollte da auch eine Liste von Sendern speichern können, damit man mehr Möglichkeiten hat. Dann würde standardmäßig immer den letzten ausgewählten Sender erscheinen und der Admin hätte noch die Möglichkeit neue Sender hinzuzufügen.

**Comment by zahnheinrich** [comment]
Danke für den Tipp! 
Ich bin begeistert von der neuen webmatic!
