### ISSUE TITLE
Sortierung (Räume/Geräte/Gewerke/Programme)

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#6]
Manuelle Sortierung der Reihenfolge in der Ansicht

**Comment by Qlink84** [comment]
Eine manuelle Sortierung der Geräte in einem Raum, wäre ebenfalls ein super Feature.

**Comment by ldittmar81** [comment]
Hi Qlink84,

das mit der Sortierung von Geräten wird in Version 2.3 drin sein... in 2.2 sind erst die Variablen dran :wink:
