### ISSUE TITLE
Nagelneue CCU2 mit Problemen

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#61]
Wenn man WebMatic auf eine neue CCU2 installiert, haben Räume und Gewerke komische Bezeichnungen. Z.B ${roomKitchen}.

Das Problem ist, dass die CCU so ein bisschen internationalisiert ist und die Räume/Gewerke in Wirklichkeit auch so heißen.

**Comment by Apollon77** [comment]
Die Lösung die ich kenne ist das man die Raumnamen einmal editieren muss und dann passt alles

**Comment by ldittmar81** [comment]
Hi Apollon77. Ja, aber wenn ein Neuling so eine CCU bekommt und vielleicht Webmatic installiert, wird er viel Suchen müssen, um das raus zu bekommen. Das Umbenennen ist zwar eine Lösung, aber keine schöne/benutzerfreundliche. :wink:

**Comment by schneiderobw** [comment]
Hier darf ich noch ein wenig Input posten, damit nicht umsonst entwickelt wird:
Das Problem dieser fehlerhaften Darstellung liegt ursächlich in der CCU als ein Bug und dürfte allseits bekannt sein.
Diese sonderbaren Bezeichnungen werden von der CCU erzeugt, bis man einmalig die Objektnamen im CCU-System die Namen editiert hat.
Diesen Punkt muss eigentlich jeder anfassen, da es nicht nur in Webmatic zu diesem Darstellungsfehler kommt.
Ich halte es nicht für notwendig, in einem Folgesystem den Bug der CCU zu korrigieren,
wenn es durch einfachen Eingriff in der CCU-Config gelöst werden kann.
Ich würd mir die Zeit für Korrektur hier ersparen.

**Comment by ldittmar81** [comment]
Hi schneiderobw. Ich gebe dir schon recht, aber ich weiss noch wie ich damals rumgesucht habe bist ich das rausgekriegt habe. Ich kann somit ein HM-Starter viel Zeit sparen und er kann die gesparte Zeit nutzen um was produktives zu machen... und außerdem ist das ein 5 Zeiler :stuck_out_tongue_winking_eye:

**Comment by ldittmar81** [comment]
Fixed with commit 30aebf119222f275c93d10e2624f793f045cc55e

Kann bitte jemand testen und mir Feedback geben? Ich habe leider keine jungfräuliche CCU.

**Comment by ldittmar81** [comment]
Ging doch nicht. Werde am Wochenende eine lxccu aufsetzen und probieren.
