### ISSUE TITLE
Neue Variablen-Typen

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#62]
Beatz hat geschrieben:
Ich hätte noch eine weitere Idee, hoffe aber, dass diese nicht zu kompliziert ist. Ich könnte mir gut vorstellen, dass man für bestimmte Formen vom Inhalt Widgets anbietet, um nicht Text zu schreiben.
Ich habe dabei ein recht konkretes Anliegen. Und zwar würde ich gern über ein Farbrad RGB-Werte in eine Variable schreiben. Ich könnte mir allerdings auch andere Inhaltstypen vorstellen, z.B. Date- und Time-Picker (falls das jemand benötigt).

**Comment by ldittmar81** [comment]
Hi Beatz,

finde die Idee super und werde es auch umsetzen. Zur Zeit existieren schon ein paar Variablen-Arten und ich werde die aktuelle Umsetzung beibehalten. Man schreibt dann einfach im Feld Einheit die Art rein. Zur Zeit existieren folgenden Typen:

Zeichenkette: 
HTML - Für HTML-Inhalte. Hier wird auch eventuelle JavaScripte nachträglich ausgeführt.
HISTORIAN - Für Diagramme aus CCU-Historian
TUNEIN - Für Radiosender

Diese werde noch hinzugefügt
DATE - Für Datum
DATETIME - Für Datum mit Uhrzeit
TIME - Für Uhrzeit
COLOR - Für Farbwerte

Werteliste:
Hier wird z.Z. eine Reihe von Buttons oder eine Selectbox angezeigt. Ich gehe hier aber nach Anzahl, was blöd ist, wenn die Bezeichnungen extrem lang oder kurz sind... ich werde noch die Möglichkeit bieten zwischen beide Manuel auszuwählen.

**Comment by schneiderobw** [comment]
Hallo ldittmar,

wenn Du grad schon beim Pixelschubsen und UI-Polish bist, hätte ich noch einen Minor-Bug im Zusammenhang mit den speziellen Datentypen bei Systemvariablen einzukippen:

Bei SysVars vom Typ Date oder Time wird im Falle von "read-only" der Setzen-Button nicht komplett ausgeblendet, sondern nur ausgegraut.
Bei allen anderen Sysvar-Typen sieht man dagegen bei "read-only" den Setzen-Button nicht.

![unbenannt](https://cloud.githubusercontent.com/assets/16177943/13711640/f21f959c-e7bf-11e5-8246-a7e0b546ce04.JPG)

Das ist nur ein minor-Bug, und wenn das auf Grund der besonderen Datentypen zu schwierig ist, dann lass es so wie es ist.

Grüße
schneider.obw

PS: DATETIME hab ich nicht getested.
