### ISSUE TITLE
Variablen (r) (w) erweitern

### ISSUE THREAD

**Issue by ldittmar81** [jens-maus/webmatic#64]
das mit dem (r) oder (w) stört mich auch  :wink: es kommt weg! Bei Version 2.2 werde ich alle (r)s und (w)s einlesen und aus der Beschreibung ausblenden. Ab Version 2.3 wird das nicht mehr unterstützt werden. So kann ich sicher stellen, dass keine Einstellung verloren geht.

Einwand:
Zum (r) (w):
Von dieser Implementierung bin ich geradezu ein Fan. Grund: Umsetzung im HM-System ohne größere Aktion, und dann gültig für alle WM-Endgeräte. Ob da nun ein r/w in der GUI dahinter steht stört mich dabei wenig. Gegenteil: dadurch wird ja auch gleich klar, dass die Variable bewusst les- bzw. schreibbar im System konfiguriert ist.
Deinen Vorschlag finde ich allerdings auch recht gut, dies zunächst weiter auszuwerten und nur die r/ws in der GUI auszublenden. Aber bitte bitte schneide diese Funktionalität in einer zukünftigen Version dann nicht komplett weg, sondern lass sie möglichst parallel zu einer neu entwickelten Lösung weiterhin gelten.

Lösung:
Wegen "readonly variablen"... mich persönlich stören diese (r). Wahrscheinlich weil ich bis vor ein paar Wochen/Monate noch nicht mit WebMatic zu tun hatte. Ist aber wie viele Sachen Geschmacksache... ich werde noch ein Systemparameter (Beschreibung von (r)s und (w)s bereinigen) erstellen und die (r)s weiterhin unterstützen... für mich wird es etwas komplizierter, denn ich werde immer an 2 Stellen schauen müssen, aber das Leben ist auch kein Ponyhof  :P

**Comment by schneiderobw** [comment]
Hey. Danke für das schnelle Umsetzen in der Alpha 2.2-1.
Jetzt habe ich meine eigene persönliche Funktionalität in der Webmatic. Prima. Bin richtig froh.
Wenn Du bitte noch ein/zwei Kleinigkeiten korrigierst:
Schreibfehler bei "Beschribung", und evtl. "Letzes Mal" groß geschrieben.

![unbenannt](https://cloud.githubusercontent.com/assets/16177943/13197077/b98ee756-d7e2-11e5-960b-b9fae97feef4.JPG)

BTW:
Ich trau mich nicht, selbst in den Code einzugreifen, weil ich auch das Konzept mit Master/Branch/Fork geschnallt habe.
Lohnt sich aber auch nicht bzw. ist eher sogar gefährlich, da ich nicht wirklich programmieren kann!!

Ansonsten nochmal Danke für die vielen neuen Features in dieser Version.
Bin grad mal so am durchspielen und durchtesten ....
