### ISSUE TITLE
Sortieroption alphabetisch für Systemvariablen

### ISSUE THREAD

**Issue by schneiderobw** [jens-maus/webmatic#68]
Für die Systemvariablen sollte die Sortieroption in Einstellungen genauso arbeiten, wie für Programme: Stellt man in den Optionen die Standardsortierung global ein auf "alphabetisch", so hat das korrekt Auswirkung auf die alphabetische Darstellung der Programmobjekte im Reiter "Programme" sowie auch unter "Optionen/Programme".
Die Systemvariablen sollten ebenfalls in den Genuss dieser Einstellung kommen (Optionen/Systemvariablen und Reiter "Systemvariablen). 
Entweder ist das ein Bug - oder es wurde im Code für die Sysvars noch nicht umgesetzt.
Ein globales Setting für Programme und Sysvars dürfte dabei ausreichen.

**Comment by ldittmar81** [comment]
Bei Sysvars wurde es noch nicht umgesetzt ;-)
