### ISSUE TITLE
[Version 2.1.4] Melden von neuen Versionen fehlerhaft

### ISSUE THREAD

**Issue by UweRP** [jens-maus/webmatic#69]
Hi!
Wird unter Einstellungen/Optionen/Sonstiges eingetragen das neue Versionen gemeldet werden sollen
wird nicht zwischen stabile und alpha unterschieden. Dort hatte ich eingestellt "nur stabile Versionen" trotzdem wird mir die 2.2Alpha1 als neue Version gemeldet.

Uwe

**Comment by ldittmar81** [comment]
Hi Uwe. Danke für die Meldung. Es ist so, dass die Logik leider umgekehrt war. Wenn man nur Stable wollte, hat man alle bekommen und wenn mann alle wollte, nur die Stable.

**Comment by ldittmar81** [comment]
Ich habe jetzt die Meldung ausgeschaltet, damit die, die nur Stable wollten sich nicht gestört füllen. Es hat aber die Nebenwirkung, dass man nicht mehr über aktuelle Alphas informiert wird. Ab Version 2.2 wird sich dann alles normalisieren. Danke.
