### ISSUE TITLE
Button für Seitenanfang in Menüleiste

### ISSUE THREAD

**Issue by schneiderobw** [jens-maus/webmatic#70]
Ich hätte noch eine Anregung/Vorschlag für ein recht einfaches Features. Ist mir aufgefallen/eingefallen bei den Scrollorgien, die ich zum Durchtesten der Alpha2.2 aktuell abhalte.
Könntest Du im Menübalken links eine Funktion für "Page to Top" einbauen, die evt. immer am unteren Rand mitwandert; so dass man mit einem Klick darauf nach oben kommt. Ich weiß: viele Browser haben dafür schon einen Shortcut, und ggfls. sogar einfach durch Fingertip auf den oberen Browserrand. Bei meinem kleinem Tablett geht das aber recht schwer mit meinen Wurstfingern - und wenn man so einen schicken Knopf hat.
Insbesondere bei dem Menü mit vielen SysVars oder auch den Programmen wäre das Teil sehr hilfreich.
Ich hab mal meinen Vorschlag in einer Zeichnung skizziert. So - oder so ähnlich:

![unbenannt](https://cloud.githubusercontent.com/assets/16177943/13197152/55e1f254-d7e5-11e5-8b0c-007b45bf2342.JPG)

Wichtig wäre, dass das Teil immer am unteren Rand klebt, und mitwandert.
Dürfte für Dich sicherlich nicht schwer sein in der Umsetzung (nachdem Du den Kampf mit den Spalten, Titanen und anderen Giganten im Code von Webmatic a schon erfolgreich gewonnen hast ;-).

**Comment by ldittmar81** [comment]
Hmm... die Menüleiste könnte per Einstellung ausgeschaltet sein. Ich lasse mir was einfallen.

**Comment by schneiderobw** [comment]
Wenn die Menüleiste aus ist (ich vermute mal Flip-Darstellung), wird ein Scroll-to-top nicht unbedingt benötigt. Da könnt ich drauf verzichten, weil ich ja mit Flip-back auch wieder zurück komme und dann neu wählen kann.
Gut wäre der Scroll-top-top-Pfeil in der linken Spalte - und quasi ständig "mitschwimmend" am unteren Rand.
Noch besser wäre, wenn die Menüleiste dann links auch immer fest stehen bleibt. Derzeit scrollt sie mit nach oben bei langen Listen auf der rechten Seite. Wär das evtl. ohne viel Umprogrammierung mit Frames machbar?
Schau mal was geht. Der Scroll-Knopf wär mir das Wichtigste.
