### ISSUE TITLE
Teiler werden bei neuen Geräten nicht angenommen - evtl. nur Problem im Debug-Modus

### ISSUE THREAD

**Issue by schneiderobw** [jens-maus/webmatic#72]
Ein kleines Problemchen habe ich aus meinen Tests zu berichten, könnte aber mit der Trunk-Version im Debug-Modus zusammenhängen:
Wenn ich auf meinen Hauptrechner (ersten Rechner) alle Teiler in den Bereichen angelegt habe, sehe ich diese im Menü wunderbar auf diesem Rechner. Sofern ich dann mit den nächsten Geräten neu anmelde, sind die Teiler-Zuordnungen für diese Geräte nicht vorhanden, und stehen alle in unsortiert. Dieser Effekt ist zumindest bei mir bei den Favoriten so (hab ich aber erstmals mit dem aktuellen Trunk der Alpha2 gestestet).
Ich war der Meinung, dies wird global festgelegt, und soll dann bei jedem nächsten Gerät von global übernommen werden (bzw. mit den "Gesamteinstellungen").

Eine andere Möglichkeit ist evtl. das "Kopieren" von Einstellungen von einem Gerät zum anderen.
Da ich die Funktion mittlerweile kapiert habe - noch ein Update hier: Wenn ich auf dem Hauptrechner (dem ersten Rechner mit allen Einstellungen) einmalig die spezifischen Einstellungen eines erstmalig neuen Gerätes lade und wieder speichere/verlasse, dann sind auch die Einstellungen für das neue Gerät ok.

Zum Thema Cache und/oder Debug-Mode:
Cache putze ich bei allen Geräten immer komplett leer, neu Update genauso wie nach Änderungen von Einstellungen.
Debug-Mode: Einen neuen Trunk spiele ich ein, indem ich - basierend auf der installierten "Urversion von Alpha2" alle Files und Unterverzeichnisse aus dem Download des Master unter webmatic hochlade. In der Regel lösche ich dann noch zusätzlich alle xxx.json mit den Einstellungen unter webmatic_user, so dass ich quasi mit der Konfiguration jungfräulich anfange. 

PS: ich kann auch gerne warten auf die nächste Alpha, und das ganze nochmal ohne Debug-Overhead durchtesten.

**Comment by ldittmar81** [comment]
Das war echt ein Ding!!! Jetzt habe ich die Antwort.... muss es jetzt nur noch umsetzen. :wink:
